CREATE TABLE "TA_ACTE"
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	"CODE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	"LIBELLE" VARCHAR2(255 BYTE) NOT NULL ENABLE,
	CONSTRAINT "TA_ACTE_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE, 
	CONSTRAINT "TA_ACTE_UK1" UNIQUE ("CODE") ENABLE
   );
   

CREATE TABLE "TA_VERSION_ACTE" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"CODE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"LIBELLE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
   	"ACTE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"NUMERO" NUMBER(1,0) NOT NULL ENABLE, 
	CONSTRAINT "TA_VERSION_ACTE_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,  
	CONSTRAINT "TA_VERSION_ACTE_UK1" UNIQUE ("ACTE", "NUMERO") ENABLE, 	 
	CONSTRAINT "TA_VERSION_ACTE_UK2" UNIQUE ("CODE") ENABLE, 
	CONSTRAINT "TA_VERSION_ACTE_FK1" FOREIGN KEY ("ACTE") REFERENCES "TA_ACTE" ("IDENTIFIANT") ENABLE
   );

   
CREATE TABLE "TA_LIGNE_DEPENSE" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"VERSION_ACTE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"ACTIVITE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"NATURE_ECONOMIQUE" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"SOURCE_FINANCEMENT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"BAILLEUR" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"AJUSTEMENT_AE" NUMBER(16,0) NOT NULL ENABLE, 
	"AJUSTEMENT_CP" NUMBER(16,0) NOT NULL ENABLE, 
	CONSTRAINT "TA_LIGNE_DEPENSE_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE, 
	CONSTRAINT "TA_LIGNE_DEPENSE_UK1" UNIQUE ("VERSION_ACTE", "ACTIVITE", "NATURE_ECONOMIQUE", "SOURCE_FINANCEMENT", "BAILLEUR") ENABLE, 
	CONSTRAINT "TA_LIGNE_DEPENSE_FK1" FOREIGN KEY ("VERSION_ACTE") REFERENCES "TA_VERSION_ACTE" ("IDENTIFIANT") ENABLE
   );
   
CREATE TABLE "TA_MOUVEMENT_CREDIT_VERS_ACTE" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE) NOT NULL ENABLE, 
	"MOUVEMENT_CREDIT" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"VERSION_ACTE" VARCHAR2(1024 BYTE) NOT NULL ENABLE, 
	"INCLUS" NUMBER(1,0), 
	CONSTRAINT "TA_MOUVEMENT_CREDIT_VERS_A_PK" PRIMARY KEY ("IDENTIFIANT") ENABLE,  
	CONSTRAINT "TA_MOUVEMENT_CREDIT_VERS__UK1" UNIQUE ("MOUVEMENT_CREDIT", "VERSION_ACTE") ENABLE,  
	CONSTRAINT "TA_MOUVEMENT_CREDIT_VERS__FK1" FOREIGN KEY ("VERSION_ACTE") REFERENCES "TA_VERSION_ACTE" ("IDENTIFIANT") ENABLE
   );
