CREATE TABLE "VA_LIGNE_DEPENSE" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE), 
	"ND_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"ND_CODE" VARCHAR2(6 CHAR), 
	"ND_CODE_LIBELLE" VARCHAR2(207 CHAR), 
	"SECTION_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"SECTION_CODE" VARCHAR2(255 CHAR), 
	"SECTION_CODE_LIBELLE" VARCHAR2(511 CHAR), 
	"UA_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"UA_CODE" VARCHAR2(20 CHAR), 
	"UA_CODE_LIBELLE" VARCHAR2(321 CHAR), 
	"USB_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"USB_CODE" VARCHAR2(9 CHAR), 
	"USB_CODE_LIBELLE" VARCHAR2(310 CHAR), 
	"ACTION_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"ACTION_CODE" VARCHAR2(255 CHAR), 
	"ACTION_CODE_LIBELLE" VARCHAR2(756 CHAR), 
	"ACTIVITE_IDENTIFIANT" VARCHAR2(55 BYTE), 
	"ACTIVITE_CODE" VARCHAR2(20 BYTE), 
	"ACTIVITE_CODE_LIBELLE" VARCHAR2(1045 BYTE), 
	"NE_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"NE_CODE" VARCHAR2(200 CHAR), 
	"NE_CODE_LIBELLE" VARCHAR2(401 CHAR), 
	"SF_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"SF_CODE" VARCHAR2(255 CHAR), 
	"SF_CODE_LIBELLE" VARCHAR2(511 CHAR), 
	"BAILLEUR_IDENTIFIANT" VARCHAR2(255 BYTE), 
	"BAILLEUR_CODE" VARCHAR2(20 BYTE), 
	"BAILLEUR_CODE_LIBELLE" VARCHAR2(276 BYTE), 
	"CA_IDENTIFIANT" VARCHAR2(20 BYTE), 
	"CA_CODE" VARCHAR2(20 BYTE), 
	"CA_CODE_LIBELLE" VARCHAR2(276 BYTE), 
	"CB_IDENTIFIANT" VARCHAR2(255 CHAR), 
	"CB_CODE" VARCHAR2(255 CHAR), 
	"CB_CODE_LIBELLE" VARCHAR2(456 CHAR), 
	
	"BUDGET_INITIAL_AE" NUMBER(19,0), 
	"BUDGET_INITIAL_CP" NUMBER(19,0), 
	"MOUVEMENT_AE" NUMBER(19,0), 
	"MOUVEMENT_CP" NUMBER(19,0), 
	"BUDGET_ACTUEL_AE" NUMBER(19,0), 
	"BUDGET_ACTUEL_CP" NUMBER(19,0), 
	"DISPONIBLE_AE" NUMBER(19,0), 
	"DISPONIBLE_CP" NUMBER(19,0)
   );
   
CREATE TABLE "VA_LIGNE_DEPENSE_MOUVEMENT_INCLUS"
   ("IDENTIFIANT" VARCHAR2(255 BYTE),
	"AE" NUMBER(19,0),
	"CP" NUMBER(19,0)
   );
   
CREATE TABLE "VA_LIGNE_DEPENSE_BUDGET_FINAL" 
   ("IDENTIFIANT" VARCHAR2(255 BYTE),
	"AE" NUMBER(19,0),
	"CP" NUMBER(19,0)
   );